# Generated by Django 3.0.7 on 2020-06-19 10:35

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='img',
            field=models.ImageField(null=True, upload_to=core.models.recipe_image_file_path),
        ),
    ]
