# Generated by Django 3.0.7 on 2020-06-19 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='img',
            new_name='image',
        ),
    ]
